name: microservice-app
services:
  discovery:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - mechanic-net

  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      URL_FRONT: http://localhost:4200
    networks:
      - mechanic-net

  main:
    build:
      context: ./principal-service
      dockerfile: Dockerfile
    container_name: principal-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/principal_db
      URL_FRONT: http://localhost:4200
    depends_on:
      - db
      - gateway
      - discovery
    networks:
      - mechanic-net

  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    image: microservice-app-order-service
    depends_on:
      - discovery
      - monguito
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
      MONGODB_URI: mongodb://monguito:27017/work_order_db?authSource=admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mechanic-net

  db:
    build:
      context: databases/db-main
      dockerfile: Dockerfile
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: principal_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mechanic-net

  monguito:
    build:
      context: databases/db-order
      dockerfile: Dockerfile
    restart: always
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mechanic-net

volumes:
  mysql_data:
  mongo_data:

networks:
  mechanic-net:
    driver: bridge